version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/bbiyong
#    overwrite: yes
#file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu/bbiyong/
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ubuntu