app:
  twitterAccessToken: ${TWITTER_ACCESS_TOKEN}
  twitterAccessTokenSecret: ${TWITTER_ACCESS_TOKEN_SECRET}
  twitterApiKey: ${TWITTER_API_KEY}
  twitterApiSecretKey: ${TWITTER_API_SECRET_KEY}
  topisApiKey : ${TOPIS_API_KEY}